#missing (changed) optional bakcup data on deploy

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -137,6 +137,7 @@ deploy_dev:
   script:
     - echo "Deploy ${VIKYAPP_DEPLOY_RANCHER_STACK} on ${RANCHER_URL}/dev ( ${CI_ENVIRONMENT_URL} )"
     - cd deployment
+    - viky_backup
     - echo "Deploy ..."
     - rancher --wait --environment dev up --stack ${VIKYAPP_DEPLOY_RANCHER_STACK} --file docker-compose.yml  --file docker-compose-infra.yml --file docker-compose-rancher.yml -d --batch-size 1 --pull --force-upgrade --confirm-upgrade --prune
 
@@ -162,8 +163,7 @@ deploy_preprod:
   script:
     - echo "Deploy ${VIKYAPP_DEPLOY_RANCHER_STACK} on ${RANCHER_URL}/dev ( ${CI_ENVIRONMENT_URL} )"
     - cd deployment
-    - echo "Backing up data ..."
-    - rancher_exec preprod ${VIKYAPP_DEPLOY_RANCHER_STACK}-backup-1 bash /backup/backup.sh
+    - viky_backup
     - echo "Deploy ..."
     - rancher --wait --environment preprod up --stack ${VIKYAPP_DEPLOY_RANCHER_STACK} --file docker-compose.yml --file docker-compose-infra.yml --file docker-compose-rancher.yml -d --batch-size 1 --pull --force-upgrade --confirm-upgrade --prune
 
@@ -315,6 +315,18 @@ backup_restore_dev:
 .auto_devops: &auto_devops |
   # Auto DevOps variables and functions
   [[ "$TRACE" == "1" ]] && set -x
+
+  function viky_backup ()
+  {
+    echo "Backing up data ..."
+    rancher_exec preprod ${VIKYAPP_DEPLOY_RANCHER_STACK}-backup-1 bash /backup/backup.sh
+
+    if [ $? -ne 0 ]; then
+      (>&2 echo "Backing up data FAILED")
+    fi
+    echo ""
+  }
+
 
   function docker_build ()
   {
